openapi: 3.0.0
info:
  version: 1.0.0
  title: API Documentation

paths:
  /api/recipes:
    post:
      tags:
        - recipes
      security:
        - BearerAuth: []
      summary: Post a new recipe
      operationId: postRecipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Recipe name
                category:
                  type: string
                  description: Recipe category
                instructions:
                  type: array
                  items:
                    type: string
                  description: Recipe instructions
                ingredients:
                  type: array
                  items:
                    type: string
                  description: Recipe ingredients
      responses:
        "200":
          description: Successful operation

    get:
      tags:
        - recipes
      summary: Get all recipes
      operationId: getAllRecipe
      responses:
        "200":
          description: Successful operation

  /api/recipes/{id}:
    get:
      tags:
        - recipes
      summary: Get a recipe by ID
      operationId: getRecipeById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the recipe to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Successful operation

    put:
      tags:
        - recipes
      security:
        - BearerAuth: []
      summary: Update a recipe by ID
      operationId: updateRecipe
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the recipe to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Recipe name
                category:
                  type: string
                  description: Recipe category
                instructions:
                  type: array
                  items:
                    type: string
                  description: Recipe instructions
                ingredients:
                  type: array
                  items:
                    type: string
                  description: Recipe ingredients
      responses:
        "200":
          description: Successful operation

    delete:
      tags:
        - recipes
      security:
        - BearerAuth: []
      summary: Delete a recipe by ID
      operationId: deleteRecipe
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the recipe to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful operation

  /:
    get:
      summary: Protected route
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Protected route accessed

  /loggout:
    get:
      summary: User logged out
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful operation

  /register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's name
                email:
                  type: string
                  format: email
                  description: User's email
                password:
                  type: string
                  description: User's password
      responses:
        "200":
          description: Successful operation

  /login:
    post:
      summary: User login
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email
                password:
                  type: string
                  description: User's password
      responses:
        "200":
          description: Successful operation

components:
  schemas:
    UserRegistration:
      type: object
      properties:
        name:
          type: string
          description: Oumaima
        email:
          type: string
          format: email
          description: Oumaima@gmail.com
        password:
          type: string
          description: Oumaima123

    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
          description: Oumaima@gmail.com
        password:
          type: string
          description: Oumaima123

    Recipe:
      type: object
      properties:
        name:
          type: string
          description: Recipe name
        category:
          type: string
          description: Recipe category
        instructions:
          type: array
          items:
            type: string
          description: Recipe instructions
        ingredients:
          type: array
          items:
            type: string
          description: Recipe ingredients

securitySchemes:
  BearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
